package com.xsl.middle_school_oa.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article_receiver
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ArticleReceiver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.read_status
     *
     * @mbg.generated
     */
    private Integer readStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.article_type_id
     *
     * @mbg.generated
     */
    private Integer articleTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.read_time
     *
     * @mbg.generated
     */
    private Date readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.read_count
     *
     * @mbg.generated
     */
    private Integer readCount;

    /**
     * Database Column Remarks:
     *   1主要2，普通
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.type
     *
     * @mbg.generated
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.article_author
     *
     * @mbg.generated
     */
    private String articleAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_receiver.dept_id
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_receiver
     *
     * @mbg.generated
     */
    public ArticleReceiver(Integer id, Integer userId, Integer readStatus, Date createTime, Integer articleId, Integer articleTypeId, Date readTime, Integer readCount, Short type, String userName, String articleTitle, String articleAuthor, Integer deptId) {
        this.id = id;
        this.userId = userId;
        this.readStatus = readStatus;
        this.createTime = createTime;
        this.articleId = articleId;
        this.articleTypeId = articleTypeId;
        this.readTime = readTime;
        this.readCount = readCount;
        this.type = type;
        this.userName = userName;
        this.articleTitle = articleTitle;
        this.articleAuthor = articleAuthor;
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_receiver
     *
     * @mbg.generated
     */
    public ArticleReceiver() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.id
     *
     * @return the value of article_receiver.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.id
     *
     * @param id the value for article_receiver.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.user_id
     *
     * @return the value of article_receiver.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.user_id
     *
     * @param userId the value for article_receiver.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.read_status
     *
     * @return the value of article_receiver.read_status
     *
     * @mbg.generated
     */
    public Integer getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.read_status
     *
     * @param readStatus the value for article_receiver.read_status
     *
     * @mbg.generated
     */
    public void setReadStatus(Integer readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.create_time
     *
     * @return the value of article_receiver.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.create_time
     *
     * @param createTime the value for article_receiver.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.article_id
     *
     * @return the value of article_receiver.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.article_id
     *
     * @param articleId the value for article_receiver.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.article_type_id
     *
     * @return the value of article_receiver.article_type_id
     *
     * @mbg.generated
     */
    public Integer getArticleTypeId() {
        return articleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.article_type_id
     *
     * @param articleTypeId the value for article_receiver.article_type_id
     *
     * @mbg.generated
     */
    public void setArticleTypeId(Integer articleTypeId) {
        this.articleTypeId = articleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.read_time
     *
     * @return the value of article_receiver.read_time
     *
     * @mbg.generated
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.read_time
     *
     * @param readTime the value for article_receiver.read_time
     *
     * @mbg.generated
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.read_count
     *
     * @return the value of article_receiver.read_count
     *
     * @mbg.generated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.read_count
     *
     * @param readCount the value for article_receiver.read_count
     *
     * @mbg.generated
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.type
     *
     * @return the value of article_receiver.type
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.type
     *
     * @param type the value for article_receiver.type
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.user_name
     *
     * @return the value of article_receiver.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.user_name
     *
     * @param userName the value for article_receiver.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.article_title
     *
     * @return the value of article_receiver.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.article_title
     *
     * @param articleTitle the value for article_receiver.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.article_author
     *
     * @return the value of article_receiver.article_author
     *
     * @mbg.generated
     */
    public String getArticleAuthor() {
        return articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.article_author
     *
     * @param articleAuthor the value for article_receiver.article_author
     *
     * @mbg.generated
     */
    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor == null ? null : articleAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_receiver.dept_id
     *
     * @return the value of article_receiver.dept_id
     *
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_receiver.dept_id
     *
     * @param deptId the value for article_receiver.dept_id
     *
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}