package com.xsl.middle_school_oa.mapper;

import com.sun.tracing.dtrace.NameAttributes;
import com.xsl.middle_school_oa.domain.ArticleFile;
import com.xsl.middle_school_oa.domain.ArticleFileExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ArticleFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    long countByExample(ArticleFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    int insert(ArticleFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    int insertSelective(ArticleFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    List<ArticleFile> selectByExample(ArticleFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    ArticleFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleFile record, @Param("example") ArticleFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleFile record, @Param("example") ArticleFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleFile record);
}